watchlist/models.py
from watchlist import db
from werkzeug.security import generate_password_hash, check_password_hash


user_movie = db.Table(
    'user_movie',
    db.Column('user_id', db.Integer, db.ForeignKey('user.id'), primary_key=True),
    db.Column('movie_id', db.Integer, db.ForeignKey('movie.id'), primary_key=True)
)


class User(db.Model):  # 表名将会是 user（自动生成，小写处理）
    __tablename__ = 'user'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)  # 主键
    name = db.Column(db.String(20))  # 名字
    _password = db.Column(db.String(16))

    movie = db.relationship('Movie', backref='user', secondary=user_movie)      #多对多关系

    @property
    def password(self):
        return self._password

    @password.setter
    def password(self, value):
        self._password = generate_password_hash(value)

    def check_password(self, user_pw):
        return check_password_hash(self._password, user_pw)



class Movie(db.Model):  # 表名将会是 movie
    __tablename__ = 'movie'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)  # 主键
    title = db.Column(db.String(60))  # 电影标题
    year = db.Column(db.String(4))  # 电影年份
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=True)

watchlist/forms.py
from wtforms.fields import simple
from wtforms import validators, Form, widgets



class Login(Form):
    username = simple.StringField(
        label='用户名',
        widget=widgets.TextInput(),
        validators=[validators.InputRequired(), validators.Length(max=20, min=1, message='长度超出！')],
        render_kw={'class': 'username', 'id': 'username'}
    )

    password = simple.PasswordField(
        label='密码',
        widget=widgets.PasswordInput(),
        validators=[validators.InputRequired(), validators.Length(max=16, min=1, message='长度超出！')],
        render_kw={'class': 'password', 'id': 'password'}
    )


class Register(Login):
    checkpassword = simple.PasswordField(
        label='确认密码',
        widget=widgets.PasswordInput(),
        validators=[validators.InputRequired(), validators.Length(max=16, min=1, message='长度超出！'), validators.EqualTo('password', message='密码必须一致！')],
        render_kw={'class': 'checkpassword', 'id': 'checkpassword'}
    )


class Movie(Form):
    title = simple.StringField(
        label='title',
        widget=widgets.TextInput(),
        validators=[validators.InputRequired(), validators.Length(max=100, min=1, message='长度超出！')],
        # render_kw={'class': 'addmovie'}
    )

    year = simple.StringField(
        label='year',
        widget=widgets.TextInput(),
        # render_kw={'class': 'addmovie'},
        validators=[validators.Length(min=4, max=4, message='输入的日期不规范！')]
    )

    id = simple.HiddenField(
        label='id',
        widget=widgets.HiddenInput(),
    )

    

watchlist/__init__.py
from flask import Flask
from config import config_map
from flask_sqlalchemy import SQLAlchemy
from flask_wtf import CSRFProtect
from flask_session import Session


db = SQLAlchemy()
session = Session()

def create_app(config_name):
    # 工厂模式
    app = Flask(__name__)
    app.config.from_object(config_map.get(config_name))

    # 绑定插件
    db.init_app(app)
    session.init_app(app)
    # CSRFProtect(app)

    # 注册蓝图
    from watchlist.views import bp_index,bp_edit
    app.register_blueprint(bp_index)
    app.register_blueprint(bp_edit)
    
    return app

watchlist/views/__init__.py
from flask import Blueprint, render_template, session, request, redirect, url_for


bp_index = Blueprint('index', __name__, url_prefix='/')
bp_edit = Blueprint('edit', __name__, url_prefix='/edit')


from . import index
from . import login
from . import register
from . import edit

watchlist/views/edit.py
from flask import render_template, request, redirect, url_for, flash, session, g

from . import bp_edit
from watchlist import models
from watchlist import forms


@bp_edit.route('/')
def edit():
    form = forms.Movie()
    
    username = session.get('username')
    user_id = models.User.query.filter(models.User.name == username).first().id
    movies = models.Movie.query.filter(models.Movie.user_id == user_id).all()

    return render_template('edit.html', form=form, movies=movies, name=username)


@bp_edit.route('add/', methods=['POST'])
def add():
    # 添加电影条目
    form = forms.Movie(formdata=request.form)

    if form.validate():
        username = session.get('username')
        user_id = models.User.query.filter(models.User.name == username).first().id
        movie = models.Movie(title=form.title.data, year=form.year.data, user_id=user_id)
        try:
            models.db.session.add(movie)
            models.db.session.commit()
        except Exception:
            return '提交失败！'
    else:
        flash('输入有误！')

    return redirect(url_for('edit.edit'))
    
        
    


@bp_edit.route('dele/<string:movie_id>', methods=['GET', 'POST'])
def dele(movie_id=None):
    movie = models.Movie.query.filter(models.Movie.id == movie_id).first()
    models.db.session.delete(movie)
    models.db.session.commit()
    flash('删除成功！')

    return redirect(url_for('edit.edit'))



@bp_edit.route('change/', methods=['POST'])
def change():
    pass


@bp_edit.before_request
def is_login():
    if session.get('username'):
        return
    
    if request.path == '/login/':
        return
    
    if request.path == '/register/':
        return
    
    return redirect(url_for('index.login'))

watchlist/views/index.py
from flask import render_template, request, redirect, url_for, flash, session, g

from . import bp_index
from watchlist import models
from watchlist import forms


@bp_index.route('')
def index():
    # 展示已登录用户待看电影
    form = forms.Movie()

    username = session.get('username')
    user_id = models.User.query.filter(models.User.name == username).first().id
    movies = models.Movie.query.filter(models.Movie.user_id == user_id).all()

    return render_template('index.html', form=form, movies=movies, name=username)

    

@bp_index.before_request
def is_login():
    if session.get('username'):
        return
    
    if request.path == '/login/':
        return
    
    if request.path == '/register/':
        return
    
    return redirect(url_for('index.login'))


@bp_index.errorhandler(404)
def page_not_found(e):
    return render_template('404.html'), 404

watchlist/views/login.py
from flask import request, render_template, flash, redirect, url_for
from flask import session
from wtforms import Form

from . import bp_index
from watchlist import models
from watchlist import forms


@bp_index.route('login/', methods=['GET', 'POST'])
def login():
    form = forms.Login()

    if request.method == 'POST':
        form = forms.Login(formdata=request.form)

        if form.validate():
            user = models.User.query.filter(models.User.name == form.username.data).first()
            
            if user:
                # 用户存在并且密码正确，跳转至index页面
                if user.check_password(form.password.data):
                    session['username'] = form.username.data
                    return redirect(url_for('index.index'))
                else:
                    flash('密码错误！')
                    return render_template('login.html', form=form)
    
            # 用户不存在跳转至注册页面
            return redirect(url_for('index.register'))
        # 输入格式错误重新加载
        return render_template('login.html', form=form)
    
    
    if request.method == 'GET':
        return render_template('login.html', form=form)

watchlist/views/register.py
from flask import request, render_template, flash, redirect, url_for, session
from wtforms import Form

from watchlist import db
from . import bp_index
from watchlist import models
from watchlist import forms


@bp_index.route('register/', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        form = forms.Register(formdata=request.form)

        if form.validate():
            user = models.User(name=form.username._value(), password=form.password._value())
            print(form.username._value(),form.password._value() )
            db.session.add(user)
            db.session.commit()
        
            flash('注册成功！跳转至index')
            
            return redirect(url_for('index.index'))
        else:
            return render_template('register.html', form=form)

    return render_template('register.html', form=forms.Register())
            

watchlist/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    {% block icon %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    {% from 'macro.html' import flash_message %}

    {% block content %}
    {% endblock %}
    
</body>
</html>

watchlist/templates/edit.html
{% extends 'base.html' %}

{% block title %}修改{% endblock %}

{% block icon %}
<link rel="icon" href="{{ url_for('static', filename='icon/增加.svg') }}">{% endblock %}

{% block content %}

<h2>
    <img src="{{ url_for('static', filename='image/扁平头像-boy 04.png') }}" alt="avatar" class="avatar"> {{ name }}'s
    watchlist
</h2>


<div>{{ movies|length }} Titles </div>


<div><!-- 添加待看电影 -->
    <form action="{{ url_for('edit.add') }}" method="post">
        <label> Title</label> {{ form.title }} {{ form.title.errors[0] }} 
        <label> Year</label> {{ form.year }} {{ form.year.errors[0] }} 
        {{ form.user_id }}
        <button type="submit">添加</button>
    </form>
</div>



<ul class="movie-list">
    <ul>
        {% for m in movies %}
        <li class="movie-list">{{ m.title }} - {{ m.year }} <a href="{{ url_for('edit.dele', movie_id=m.id) }}">删除</a></li>
        {% endfor %}
    </ul>
</ul>




{% endblock %}

watchlist/templates/index.html
{% extends 'base.html' %}

{% block title %}主页{% endblock %}

{% block icon %}<link rel="icon" href="{{ url_for('static', filename='icon/首页.svg') }}">{% endblock %}

{% block content %}

<h2>
    <img src="{{ url_for('static', filename='image/扁平头像-boy 04.png') }}" alt="avatar" class="avatar">  {{ name }}'s watchlist
</h2>


{{ movies|length }} Titles     <a href="{{ url_for('edit.edit') }}">编辑</a>


<ul class="movie-list">
    <ul>
        {% for m in movies %}
        <li class="movie-list">{{ m.title }} - {{ m.year }}</li>
        {% endfor %}
    </ul>
</ul>


{% endblock %}

watchlist/templates/login.html
{% extends 'base.html' %}


{% block title %}登录{% endblock %}

{% block content %}

{{ flash_message() }}

<form action="/login/" method="post">
    <div> {{ form.username.label }} {{ form.username }} {{ form.username.errors[0] }}</div>
    <div>{{ form.password.label }} {{ form.password }} {{ form.password.errors[0] }}</div>
    <button type="submit">登录</button>
</form>

{% endblock %}

watchlist/templates/macro.html
{% macro flash_message() %}

{% for message in get_flashed_messages() %}
    <div class="alert">{{ message }}</div>
{% endfor %}

{% endmacro %}

watchlist/templates/register.html
{% extends 'base.html' %}


{% block title %}注册{% endblock %}


{% block content %}

{{ flash_message() }}

<form action="/register/" method="post">
    <div> {{ form.username.label }} {{ form.username }} {{ form.username.errors[0] }}</div>
    <div>{{ form.password.label }} {{ form.password }} {{ form.password.errors[0] }}</div>
    <div>{{ form.checkpassword.label }} {{ form.checkpassword }} {{ form.checkpassword.errors[0] }}</div>

    <button type="submit">注册</button>  <button type="reset">重置</button>
</form>

{% endblock %}